<h1>HALLOOO MENEER HOE GAAT HET ERMEE LEEFT U NOG???</h1>


<h2 class="KaasBaas">Jammer dat we dit jaar niet meer les konden krijgen maar is niet erg
<br>Ik zie u toch weer volgend jaar als t goed is
<br title="KAAS">Nou dit is dus me website we houde hier van kaas want dat is de baas</h2>

<iframe class="Discord" src="https://discord.com/widget?id=713771509646098452&theme=dark" width="300" height="380" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
<iframe class="Spotify" src="https://open.spotify.com/embed/playlist/2YvyKJLVsgTsIAq8S3VMUI" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
<iframe class="Dynmap" src="http://lucstoffels.nl:8123/" width="700" height="500"></iframe>
