

<h1 class="LOGO_hoofdtekst">Dit is mijn LOGO opdracht <h1>

<h2 class="LOGO_txt">Dit is het resultaat van mijn huis in LOGO:</h2>
  <a href="img/logo_huis.jpg" target="_blank" border="0"><img class="LOGO_ontwerp" src="img/logo_huis.jpg"></a>

<h3 class="LGO_download">Dit is het LOGO bestand--> (<a class="klik" href="files/huis.LGO" download><strong>Klik mij!</strong></a>)</h3>

<h4 class="schets_txt">Dit is mijn schets van het huis:</h4>
  <a href="img/logo_schets.png" target="_blank" border="0"><img class="LOGO_schets" src="img/logo_schets.png"></a>

<h5 class="Resize_txt">Dit is de code die je kunt copy pasten:</h5>
<div class="ResizeLOGO">
  <p>to foundation <br>
  cs <br>
  setpensize [1 1] <br>
  setpc [0 0 0] <br>
  pd <br>
  Repeat 2 [fd 200 lt 90 fd 350 lt 90] <br>
  pu <br>
  fd 200 <br>
  pd <br>
  fd 120 <br>
  lt 90 <br>
  fd 350 <br>
  lt 90 <br>
  fd 120 <br>
  pu <br>
  lt 90 <br>
  fd 350 <br>
  rt 90 <br>
  pd <br>
  fd 70 <br>
  lt 90 <br>
  fd 180 <br>
  rt 90 <br>
  fd 120 <br>
  rt 90 <br>
  fd 180 <br>
<br>
  pu <br>
  rt 90<br>
  fd 20<br>
  rt 90<br>
  fd 20<br>
  pd<br>
  Repeat 2 [fd 140 lt 90  fd 80 lt 90]<br>
  lt 90<br>
  fd 20<br>
  rt 90<br>
  fd 140<br>
  rt 180<br>
  fd 140<br>
  rt 90<br>
  rt 90<br>
  fd 140<br>
  lt 90<br>
  fd 20<br>
  lt 90<br>
  fd 140<br>
  rt 90<br>
  fd 20<br>
  rt 90<br>
  fd 140<br>
  rt 90<br>
  fd 78<br>
  rt 90<br>
  fd 140<br>
  rt 90<br>
  fd 78<br>
  pu<br>
  home<br>
  pd<br>
  fd 110<br>
  lt 90<br>
  fd 350<br>
  pu<br>
  home<br>
  setxy -340 290<br>
  pd<br>
  fd 60<br>
  lt 90<br>
  fd 5<br>
  rt 90<br>
  fd 5<br>
  rt 90<br>
  fd 30<br>
  rt 90<br>
  fd 5<br>
  rt 90<br>
  fd 5<br>
  lt 90<br>
  fd 60<br>
  rt 90<br>
  fd 20<br>
  end<br>
<br>
  to kleur<br>
  pu<br>
  home<br>
  fd 20<br>
  rt 90<br>
  fd 80<br>
  lt 90<br>
  setfc [179 195 196]<br>
  fill<br>
  Repeat 4 [fd 20 fill]<br>
  rt 90<br>
  fd 85<br>
  setfc [99 52 1]<br>
  fill<br>
  setxy -150 50<br>
  setfc [122 63 0]<br>
  fill<br>
  lt 90<br>
  fd 100<br>
  fill<br>
  fd 100<br>
  setfc[150 45 0]<br>
  fill<br>
  setxy -335 325<br>
  setfc [64 64 64]<br>
  fill<br>
  setxy -335 300<br>
  fill<br>
  end<br>
<br>
  to ramen<br>
  pu<br>
  home<br>
  setxy -320 30<br>
  pd<br>
  repeat 2 [fd 60 rt 90 fd 110 rt 90]<br>
  pu<br>
  setxy -310 40<br>
  setfc [138 204 209]<br>
  fill<br>
  setxy -80 40<br>
  pd<br>
  setpensize [5 5]<br>
  setpc [87 87 87]<br>
  repeat 2 [fd 40 rt 90 fd 20 rt 90]<br>
  pu<br>
  setxy -70 50<br>
  fill<br>
  setxy -330 130<br>
  pd<br>
  rt 90<br>
  setpensize [8 8]<br>
  setpc [143 143 143]<br>
  fd 130<br>
  setpensize [1 1]<br>
  rt 180<br>
  fd 10<br>
  rt 90<br>
  fd 60<br>
  lt 90<br>
  fd 110<br>
  lt 90<br>
  fd 60<br>
  pu<br>
  setxy -300 150<br>
  fill<br>
  setxy -265 130<br>
  pd<br>
  rt 180<br>
  fd 60<br>
  rt 180<br>
  pu<br>
  setpensize [8 8]<br>
  setxy -110 130<br>
  pd<br>
  lt 90<br>
  fd 90<br>
  setpensize [1 1]<br>
  rt 180<br>
  fd 5<br>
  rt 90<br>
  fd 50<br>
  lt 90<br>
  fd 80<br>
  lt 90<br>
  fd 50<br>
  pu<br>
  setxy -100 150<br>
  fill<br>
  end<br>
<br>



  to boom<br>
  pu<br>
  home<br>
  setxy -370 -60<br>
  pd<br>
  setpensize [15 15]<br>
  setpc [87 35 0]<br>
  fd 130<br>
  pu<br>
  fd 30<br>
  pd<br>
  setpensize [2 2]<br>
  setpc [0 87 13]<br>
  circle 60<br>
  pu<br>
  setfc [0 128 19]<br>
  fill<br>
  setxy -370 60<br>
  fill<br>
  setxy -350 60<br>
  fill<br>
  setxy -340 60<br>
  fill<br>
  setxy -340 120<br>
  fill<br>
  setxy -330 130<br>
  fill<br>
  setxy -320 80<br>
  fill<br>
  setxy -315 80<br>
  fill<br>
  setxy -370 40<br>
  end<br>
<br>
  to sfeer<br>
  pu<br>
  home<br>
  setxy -430 430<br>
  pd<br>
  setpensize [2 2]<br>
  setpc [255 166 0]<br>
  circle 30+random 50<br>
  setfc [255 234 0]<br>
  fill<br>
  pu<br>
  setxy 200 430<br>
  setfc [213 236 237]<br>
  fill<br>
  end<br>
<br>

  to final<br>
  foundation<br>
  kleur<br>
  ramen<br>
  boom<br>
  sfeer<br>
  hideturtle<br>
  end<br>
</p>
</div>
