<h1>Dit is mijn ontwerp voor de HTML 5 website.</h1>
          <a href="img/ontwerp.jpg" target="_blank" border="0"><img class="ontwerp" src="img/ontwerp.jpg"></a>

          <h2 class="resultaatPC_txt">Dit is hoe de website op mijn PC eruit ziet.</h2>
          <a href="img/resultaatPC.jpg" target="_blank" border="0"><img class="resultaatPC" src="img/resultaatPC.jpg"></a>

          <h2 class="resultaatTEL_txt">Dit is hoe de website op mijn telefoon eruit ziet.</h2>
          <a href="img/resultaatTEL.jpg" target="_blank" border="0"><img class="resultaatTEL" src="img/resultaatTEL.jpg"></a>