<ul>
            <li>Ik heb de bestanden van de schakelingen niet opgeslagen.</li>
            <li>Mijn eerste website --> (<a class="klik" href="files/website1/index.html"><strong>Klik mij!</strong></a>)</li>
            <li>Mijn tweede (HTML5) website --> (<a class="klik" href="files/website2/index.html"><strong>Klik mij!</strong></a>)</li>
            <li>De rekenmachine opdracht --> (<a class="klik" href="rekenmachine.html"><strong>Klik mij!</strong></a>)</li>
            <li>De LOGO opdracht --> (<a class="klik" href="index.php?page=6"><strong>Klik mij!</strong></a>)</li>
          </ul>
